domain: "${DOMAIN}"

serviceName: "uiremote"
serviceVersion: ${UIREMOTE_VERSION}

image:
  registry: "${CI_REGISTRY}"
  repository: "lowcode/projects/kazan-expo"
  imageName: "ui-remote"
  credentials:
    username: "${CI_REGISTRY_USERNAME}"
    password: "${CI_REGISTRY_TOKEN}"

s3UploadEndpoint: "http://minio.expo.kzn"
s3DownloadEndpoint: "http://minio.expo.kzn"
s3Bucket: "${PROJECT_NAME}-files-public"
s3Region: "us-east-1"
s3SigningRegion: "us-east-1"
s3BasePath: "remotes"
s3KeyId: "${CI_S3_KEY_ID}"
s3Key: "${CI_S3_KEY}"
service:
  httpExternalPort: 80
ingress:
  backendProtocol: "HTTP"
